/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef message_TYPES_H
#define message_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




struct MessageType {
  enum type {
    COMMAND = 0,
    DATA = 1,
    ACKNOWLEDGEMENT = 2
  };
};

extern const std::map<int, const char*> _MessageType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const MessageType::type& val);

std::string to_string(const MessageType::type& val);

class Message;

typedef struct _Message__isset {
  _Message__isset() : type(false), parity(false), payload(false) {}
  bool type :1;
  bool parity :1;
  bool payload :1;
} _Message__isset;

class Message : public virtual ::apache::thrift::TBase {
 public:

  Message(const Message&);
  Message& operator=(const Message&);
  Message() noexcept
          : type(static_cast<MessageType::type>(0)),
            parity(),
            payload() {
  }

  virtual ~Message() noexcept;
  /**
   * 
   * @see MessageType
   */
  MessageType::type type;
  std::string parity;
  std::string payload;

  _Message__isset __isset;

  void __set_type(const MessageType::type val);

  void __set_parity(const std::string& val);

  void __set_payload(const std::string& val);

  bool operator == (const Message & rhs) const
  {
    if (!(type == rhs.type))
      return false;
    if (!(parity == rhs.parity))
      return false;
    if (!(payload == rhs.payload))
      return false;
    return true;
  }
  bool operator != (const Message &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Message &a, Message &b);

std::ostream& operator<<(std::ostream& out, const Message& obj);



#endif